services:
  optimize-service:
    build:
      context: ./optimize-service
      dockerfile: Dockerfile
    volumes:
      - ./optimize-service:/app
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
 
  kong:
    image: kong:3.8
    volumes:
      - ./kong/go-auth:/usr/local/bin/go-auth 
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PLUGINS=go-auth
      - KONG_PLUGINSERVER_NAMES=go-auth
      - KONG_PLUGINSERVER_GO_AUTH_QUERY_CMD=/usr/local/bin/go-auth -dump
      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8002:8002"
      
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"