version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: Ahmedcar566
      POSTGRES_DB: vidflow
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio-data:/data:rw
    ports:
      - "9000:9000"
    command: server /data
    entrypoint: |
      /usr/bin/minio server /data &&
      /usr/bin/mc mb minio/videos


volumes:
  pgdata:
  minio-data:

