version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: mohamed
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: vidflow
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


volumes:
  mysql_data:
  minio_data:

