// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: src/proto/thumbnail.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "thumbnail";

export interface UploadThumbnailRequest {
  videoId: string;
  thumbnailObjectId: string;
  originalFilename: string;
  fileSize: number;
  contentType: string;
}

export interface UploadThumbnailResponse {
  success: boolean;
  message: string;
}

export interface GetThumbnailRequest {
  videoId: string;
}

export interface GetThumbnailResponse {
  videoId: string;
  thumbnailObjectId: string;
  thumbnailUrl: string;
  hasThumbnail: boolean;
}

function createBaseUploadThumbnailRequest(): UploadThumbnailRequest {
  return { videoId: "", thumbnailObjectId: "", originalFilename: "", fileSize: 0, contentType: "" };
}

export const UploadThumbnailRequest: MessageFns<UploadThumbnailRequest> = {
  encode(message: UploadThumbnailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.videoId !== "") {
      writer.uint32(10).string(message.videoId);
    }
    if (message.thumbnailObjectId !== "") {
      writer.uint32(18).string(message.thumbnailObjectId);
    }
    if (message.originalFilename !== "") {
      writer.uint32(26).string(message.originalFilename);
    }
    if (message.fileSize !== 0) {
      writer.uint32(32).int64(message.fileSize);
    }
    if (message.contentType !== "") {
      writer.uint32(42).string(message.contentType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadThumbnailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadThumbnailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.videoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.thumbnailObjectId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.originalFilename = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.fileSize = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadThumbnailRequest {
    return {
      videoId: isSet(object.videoId) ? globalThis.String(object.videoId) : "",
      thumbnailObjectId: isSet(object.thumbnailObjectId) ? globalThis.String(object.thumbnailObjectId) : "",
      originalFilename: isSet(object.originalFilename) ? globalThis.String(object.originalFilename) : "",
      fileSize: isSet(object.fileSize) ? globalThis.Number(object.fileSize) : 0,
      contentType: isSet(object.contentType) ? globalThis.String(object.contentType) : "",
    };
  },

  toJSON(message: UploadThumbnailRequest): unknown {
    const obj: any = {};
    if (message.videoId !== "") {
      obj.videoId = message.videoId;
    }
    if (message.thumbnailObjectId !== "") {
      obj.thumbnailObjectId = message.thumbnailObjectId;
    }
    if (message.originalFilename !== "") {
      obj.originalFilename = message.originalFilename;
    }
    if (message.fileSize !== 0) {
      obj.fileSize = Math.round(message.fileSize);
    }
    if (message.contentType !== "") {
      obj.contentType = message.contentType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadThumbnailRequest>, I>>(base?: I): UploadThumbnailRequest {
    return UploadThumbnailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadThumbnailRequest>, I>>(object: I): UploadThumbnailRequest {
    const message = createBaseUploadThumbnailRequest();
    message.videoId = object.videoId ?? "";
    message.thumbnailObjectId = object.thumbnailObjectId ?? "";
    message.originalFilename = object.originalFilename ?? "";
    message.fileSize = object.fileSize ?? 0;
    message.contentType = object.contentType ?? "";
    return message;
  },
};

function createBaseUploadThumbnailResponse(): UploadThumbnailResponse {
  return { success: false, message: "" };
}

export const UploadThumbnailResponse: MessageFns<UploadThumbnailResponse> = {
  encode(message: UploadThumbnailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadThumbnailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadThumbnailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadThumbnailResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: UploadThumbnailResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadThumbnailResponse>, I>>(base?: I): UploadThumbnailResponse {
    return UploadThumbnailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadThumbnailResponse>, I>>(object: I): UploadThumbnailResponse {
    const message = createBaseUploadThumbnailResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGetThumbnailRequest(): GetThumbnailRequest {
  return { videoId: "" };
}

export const GetThumbnailRequest: MessageFns<GetThumbnailRequest> = {
  encode(message: GetThumbnailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.videoId !== "") {
      writer.uint32(10).string(message.videoId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetThumbnailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetThumbnailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.videoId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetThumbnailRequest {
    return { videoId: isSet(object.videoId) ? globalThis.String(object.videoId) : "" };
  },

  toJSON(message: GetThumbnailRequest): unknown {
    const obj: any = {};
    if (message.videoId !== "") {
      obj.videoId = message.videoId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetThumbnailRequest>, I>>(base?: I): GetThumbnailRequest {
    return GetThumbnailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetThumbnailRequest>, I>>(object: I): GetThumbnailRequest {
    const message = createBaseGetThumbnailRequest();
    message.videoId = object.videoId ?? "";
    return message;
  },
};

function createBaseGetThumbnailResponse(): GetThumbnailResponse {
  return { videoId: "", thumbnailObjectId: "", thumbnailUrl: "", hasThumbnail: false };
}

export const GetThumbnailResponse: MessageFns<GetThumbnailResponse> = {
  encode(message: GetThumbnailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.videoId !== "") {
      writer.uint32(10).string(message.videoId);
    }
    if (message.thumbnailObjectId !== "") {
      writer.uint32(18).string(message.thumbnailObjectId);
    }
    if (message.thumbnailUrl !== "") {
      writer.uint32(26).string(message.thumbnailUrl);
    }
    if (message.hasThumbnail !== false) {
      writer.uint32(32).bool(message.hasThumbnail);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetThumbnailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetThumbnailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.videoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.thumbnailObjectId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.thumbnailUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasThumbnail = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetThumbnailResponse {
    return {
      videoId: isSet(object.videoId) ? globalThis.String(object.videoId) : "",
      thumbnailObjectId: isSet(object.thumbnailObjectId) ? globalThis.String(object.thumbnailObjectId) : "",
      thumbnailUrl: isSet(object.thumbnailUrl) ? globalThis.String(object.thumbnailUrl) : "",
      hasThumbnail: isSet(object.hasThumbnail) ? globalThis.Boolean(object.hasThumbnail) : false,
    };
  },

  toJSON(message: GetThumbnailResponse): unknown {
    const obj: any = {};
    if (message.videoId !== "") {
      obj.videoId = message.videoId;
    }
    if (message.thumbnailObjectId !== "") {
      obj.thumbnailObjectId = message.thumbnailObjectId;
    }
    if (message.thumbnailUrl !== "") {
      obj.thumbnailUrl = message.thumbnailUrl;
    }
    if (message.hasThumbnail !== false) {
      obj.hasThumbnail = message.hasThumbnail;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetThumbnailResponse>, I>>(base?: I): GetThumbnailResponse {
    return GetThumbnailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetThumbnailResponse>, I>>(object: I): GetThumbnailResponse {
    const message = createBaseGetThumbnailResponse();
    message.videoId = object.videoId ?? "";
    message.thumbnailObjectId = object.thumbnailObjectId ?? "";
    message.thumbnailUrl = object.thumbnailUrl ?? "";
    message.hasThumbnail = object.hasThumbnail ?? false;
    return message;
  },
};

export interface ThumbnailService {
  UploadThumbnail(request: UploadThumbnailRequest): Promise<UploadThumbnailResponse>;
  GetThumbnail(request: GetThumbnailRequest): Promise<GetThumbnailResponse>;
}

export const ThumbnailServiceServiceName = "thumbnail.ThumbnailService";
export class ThumbnailServiceClientImpl implements ThumbnailService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ThumbnailServiceServiceName;
    this.rpc = rpc;
    this.UploadThumbnail = this.UploadThumbnail.bind(this);
    this.GetThumbnail = this.GetThumbnail.bind(this);
  }
  UploadThumbnail(request: UploadThumbnailRequest): Promise<UploadThumbnailResponse> {
    const data = UploadThumbnailRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UploadThumbnail", data);
    return promise.then((data) => UploadThumbnailResponse.decode(new BinaryReader(data)));
  }

  GetThumbnail(request: GetThumbnailRequest): Promise<GetThumbnailResponse> {
    const data = GetThumbnailRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetThumbnail", data);
    return promise.then((data) => GetThumbnailResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
