// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: proto/thumbnail.proto

package thumbnail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadThumbnailRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoId           string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ThumbnailObjectId string                 `protobuf:"bytes,2,opt,name=thumbnail_object_id,json=thumbnailObjectId,proto3" json:"thumbnail_object_id,omitempty"`
	OriginalFilename  string                 `protobuf:"bytes,3,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	FileSize          int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ContentType       string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadThumbnailRequest) Reset() {
	*x = UploadThumbnailRequest{}
	mi := &file_proto_thumbnail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadThumbnailRequest) ProtoMessage() {}

func (x *UploadThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thumbnail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadThumbnailRequest.ProtoReflect.Descriptor instead.
func (*UploadThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_proto_thumbnail_proto_rawDescGZIP(), []int{0}
}

func (x *UploadThumbnailRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UploadThumbnailRequest) GetThumbnailObjectId() string {
	if x != nil {
		return x.ThumbnailObjectId
	}
	return ""
}

func (x *UploadThumbnailRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *UploadThumbnailRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadThumbnailRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadThumbnailResponse) Reset() {
	*x = UploadThumbnailResponse{}
	mi := &file_proto_thumbnail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadThumbnailResponse) ProtoMessage() {}

func (x *UploadThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thumbnail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadThumbnailResponse.ProtoReflect.Descriptor instead.
func (*UploadThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_proto_thumbnail_proto_rawDescGZIP(), []int{1}
}

func (x *UploadThumbnailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadThumbnailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailRequest) Reset() {
	*x = GetThumbnailRequest{}
	mi := &file_proto_thumbnail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailRequest) ProtoMessage() {}

func (x *GetThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thumbnail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_proto_thumbnail_proto_rawDescGZIP(), []int{2}
}

func (x *GetThumbnailRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetThumbnailResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoId           string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ThumbnailObjectId string                 `protobuf:"bytes,2,opt,name=thumbnail_object_id,json=thumbnailObjectId,proto3" json:"thumbnail_object_id,omitempty"`
	ThumbnailUrl      string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	HasThumbnail      bool                   `protobuf:"varint,4,opt,name=has_thumbnail,json=hasThumbnail,proto3" json:"has_thumbnail,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetThumbnailResponse) Reset() {
	*x = GetThumbnailResponse{}
	mi := &file_proto_thumbnail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailResponse) ProtoMessage() {}

func (x *GetThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thumbnail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailResponse.ProtoReflect.Descriptor instead.
func (*GetThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_proto_thumbnail_proto_rawDescGZIP(), []int{3}
}

func (x *GetThumbnailResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetThumbnailResponse) GetThumbnailObjectId() string {
	if x != nil {
		return x.ThumbnailObjectId
	}
	return ""
}

func (x *GetThumbnailResponse) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *GetThumbnailResponse) GetHasThumbnail() bool {
	if x != nil {
		return x.HasThumbnail
	}
	return false
}

var File_proto_thumbnail_proto protoreflect.FileDescriptor

const file_proto_thumbnail_proto_rawDesc = "" +
	"\n" +
	"\x15proto/thumbnail.proto\x12\tthumbnail\"\xd0\x01\n" +
	"\x16UploadThumbnailRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12.\n" +
	"\x13thumbnail_object_id\x18\x02 \x01(\tR\x11thumbnailObjectId\x12+\n" +
	"\x11original_filename\x18\x03 \x01(\tR\x10originalFilename\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"M\n" +
	"\x17UploadThumbnailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x13GetThumbnailRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"\xab\x01\n" +
	"\x14GetThumbnailResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12.\n" +
	"\x13thumbnail_object_id\x18\x02 \x01(\tR\x11thumbnailObjectId\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x12#\n" +
	"\rhas_thumbnail\x18\x04 \x01(\bR\fhasThumbnail2\xc1\x01\n" +
	"\x10ThumbnailService\x12Z\n" +
	"\x0fUploadThumbnail\x12!.thumbnail.UploadThumbnailRequest\x1a\".thumbnail.UploadThumbnailResponse\"\x00\x12Q\n" +
	"\fGetThumbnail\x12\x1e.thumbnail.GetThumbnailRequest\x1a\x1f.thumbnail.GetThumbnailResponse\"\x00B\x11Z\x0fproto/thumbnailb\x06proto3"

var (
	file_proto_thumbnail_proto_rawDescOnce sync.Once
	file_proto_thumbnail_proto_rawDescData []byte
)

func file_proto_thumbnail_proto_rawDescGZIP() []byte {
	file_proto_thumbnail_proto_rawDescOnce.Do(func() {
		file_proto_thumbnail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thumbnail_proto_rawDesc), len(file_proto_thumbnail_proto_rawDesc)))
	})
	return file_proto_thumbnail_proto_rawDescData
}

var file_proto_thumbnail_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_thumbnail_proto_goTypes = []any{
	(*UploadThumbnailRequest)(nil),  // 0: thumbnail.UploadThumbnailRequest
	(*UploadThumbnailResponse)(nil), // 1: thumbnail.UploadThumbnailResponse
	(*GetThumbnailRequest)(nil),     // 2: thumbnail.GetThumbnailRequest
	(*GetThumbnailResponse)(nil),    // 3: thumbnail.GetThumbnailResponse
}
var file_proto_thumbnail_proto_depIdxs = []int32{
	0, // 0: thumbnail.ThumbnailService.UploadThumbnail:input_type -> thumbnail.UploadThumbnailRequest
	2, // 1: thumbnail.ThumbnailService.GetThumbnail:input_type -> thumbnail.GetThumbnailRequest
	1, // 2: thumbnail.ThumbnailService.UploadThumbnail:output_type -> thumbnail.UploadThumbnailResponse
	3, // 3: thumbnail.ThumbnailService.GetThumbnail:output_type -> thumbnail.GetThumbnailResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_thumbnail_proto_init() }
func file_proto_thumbnail_proto_init() {
	if File_proto_thumbnail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thumbnail_proto_rawDesc), len(file_proto_thumbnail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thumbnail_proto_goTypes,
		DependencyIndexes: file_proto_thumbnail_proto_depIdxs,
		MessageInfos:      file_proto_thumbnail_proto_msgTypes,
	}.Build()
	File_proto_thumbnail_proto = out.File
	file_proto_thumbnail_proto_goTypes = nil
	file_proto_thumbnail_proto_depIdxs = nil
}
