root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp","video"]
  delay = 1000
  stop_on_error = true