// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quality int32

const (
	Quality_p144  Quality = 0
	Quality_p240  Quality = 1
	Quality_p360  Quality = 2
	Quality_p480  Quality = 3
	Quality_p720  Quality = 4
	Quality_p1080 Quality = 5
)

// Enum value maps for Quality.
var (
	Quality_name = map[int32]string{
		0: "p144",
		1: "p240",
		2: "p360",
		3: "p480",
		4: "p720",
		5: "p1080",
	}
	Quality_value = map[string]int32{
		"p144":  0,
		"p240":  1,
		"p360":  2,
		"p480":  3,
		"p720":  4,
		"p1080": 5,
	}
)

func (x Quality) Enum() *Quality {
	p := new(Quality)
	*p = x
	return p
}

func (x Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_video_proto_enumTypes[0].Descriptor()
}

func (Quality) Type() protoreflect.EnumType {
	return &file_video_proto_enumTypes[0]
}

func (x Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quality.Descriptor instead.
func (Quality) EnumDescriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVideoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type VideoQuality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       Quality                `protobuf:"varint,1,opt,name=quality,proto3,enum=video.Quality" json:"quality,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoQuality) Reset() {
	*x = VideoQuality{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoQuality) ProtoMessage() {}

func (x *VideoQuality) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoQuality.ProtoReflect.Descriptor instead.
func (*VideoQuality) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *VideoQuality) GetQuality() Quality {
	if x != nil {
		return x.Quality
	}
	return Quality_p144
}

func (x *VideoQuality) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoQuality) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type VideoReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Quality       []*VideoQuality        `protobuf:"bytes,2,rep,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoReadyRequest) Reset() {
	*x = VideoReadyRequest{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoReadyRequest) ProtoMessage() {}

func (x *VideoReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoReadyRequest.ProtoReflect.Descriptor instead.
func (*VideoReadyRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *VideoReadyRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoReadyRequest) GetQuality() []*VideoQuality {
	if x != nil {
		return x.Quality
	}
	return nil
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x05video\"\x0f\n" +
	"\rVideoResponse\"?\n" +
	"\x12CreateVideoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"k\n" +
	"\fVideoQuality\x12(\n" +
	"\aquality\x18\x01 \x01(\x0e2\x0e.video.QualityR\aquality\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"]\n" +
	"\x11VideoReadyRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12-\n" +
	"\aquality\x18\x02 \x03(\v2\x13.video.VideoQualityR\aquality*F\n" +
	"\aQuality\x12\b\n" +
	"\x04p144\x10\x00\x12\b\n" +
	"\x04p240\x10\x01\x12\b\n" +
	"\x04p360\x10\x02\x12\b\n" +
	"\x04p480\x10\x03\x12\b\n" +
	"\x04p720\x10\x04\x12\t\n" +
	"\x05p1080\x10\x052\x94\x01\n" +
	"\fVideoService\x12@\n" +
	"\vCreateVideo\x12\x19.video.CreateVideoRequest\x1a\x14.video.VideoResponse\"\x00\x12B\n" +
	"\x0eMakeVideoReady\x12\x18.video.VideoReadyRequest\x1a\x14.video.VideoResponse\"\x00B\rZ\vproto/videob\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_video_proto_goTypes = []any{
	(Quality)(0),               // 0: video.Quality
	(*VideoResponse)(nil),      // 1: video.VideoResponse
	(*CreateVideoRequest)(nil), // 2: video.CreateVideoRequest
	(*VideoQuality)(nil),       // 3: video.VideoQuality
	(*VideoReadyRequest)(nil),  // 4: video.VideoReadyRequest
}
var file_video_proto_depIdxs = []int32{
	0, // 0: video.VideoQuality.quality:type_name -> video.Quality
	3, // 1: video.VideoReadyRequest.quality:type_name -> video.VideoQuality
	2, // 2: video.VideoService.CreateVideo:input_type -> video.CreateVideoRequest
	4, // 3: video.VideoService.MakeVideoReady:input_type -> video.VideoReadyRequest
	1, // 4: video.VideoService.CreateVideo:output_type -> video.VideoResponse
	1, // 5: video.VideoService.MakeVideoReady:output_type -> video.VideoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		EnumInfos:         file_video_proto_enumTypes,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
