/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VideoIndexImport } from './routes/video/index'
import { Route as VideoUploadImport } from './routes/video/upload'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VideoIndexRoute = VideoIndexImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRoute,
} as any)

const VideoUploadRoute = VideoUploadImport.update({
  id: '/video/upload',
  path: '/video/upload',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/video/upload': {
      id: '/video/upload'
      path: '/video/upload'
      fullPath: '/video/upload'
      preLoaderRoute: typeof VideoUploadImport
      parentRoute: typeof rootRoute
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video/upload': typeof VideoUploadRoute
  '/video': typeof VideoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video/upload': typeof VideoUploadRoute
  '/video': typeof VideoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/video/upload': typeof VideoUploadRoute
  '/video/': typeof VideoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video/upload' | '/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video/upload' | '/video'
  id: '__root__' | '/' | '/video/upload' | '/video/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoUploadRoute: typeof VideoUploadRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoUploadRoute: VideoUploadRoute,
  VideoIndexRoute: VideoIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/video/upload",
        "/video/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/video/upload": {
      "filePath": "video/upload.tsx"
    },
    "/video/": {
      "filePath": "video/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
